.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 kokoye2007 <kokoye2007@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH 2048 6 "January 22 2020"
.SH NAME
2048 \- Simple number game for the text console
.SH SYNOPSIS
.B 2048
.RI [ blackwhite ] 
.br
.B 2048
.RI [ bluered ] 
.br
.B 2048
.RI [ test ] 
.SH DESCRIPTION
You can move the tiles in four directions using the arrow keys: up, down, left, and right. All numbers on the board will slide into that direction until they hit the wall and if they bump into each other then two numbers will be combined into one if they have the same value. Each number will only be combined once per move. Every move a new number 2 or 4 appears. If you have a 2048 on the board you have won, but you lose once the board is full and you cannot make a move.
.B 
"Blue to Red and Black to White Scheme 256 Colors"

.PP
.SH OPTIONS
These programs follow the two options 
colours choose for blue to red and black to white.
.TP
.B balckwhite
Black to White Colour Scheme. need 256 colour.
.TP
.B bluered
Black to White Colour Scheme. need 256 colour.
.SH SEE ALSO
.BR 2048-qt (1),
.BR gnome-2048 (1).
.br
The programs are documented fully by
.IR "2048" ,
available via the Info system.
.SH AUTHOR
2048 was created by mevdschee, debian 
upstream by kokoye2007.

.PP
This manual page was written by kokoye2007.
