.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 kokoye2007 <kokoye2007@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH 2048 SECTION "January 22 2020"
.SH NAME
2048 \- Simple number game for the text console
.SH SYNOPSIS
.B 2048
.RI [ blackwhite ] 
.br
.B 2048
.RI [ bluered ] 
.br
.B 2048
.RI [ test ] 
.SH DESCRIPTION
This manual page documents briefly the
.B 2048
use with 
.B 
"Blue to Red and Black to White Scheme 256 Colors"

.PP
\fB2048\fP is a just game program that...
.SH OPTIONS
These programs follow the two options 
colours choose for blue to red and black to white.
.TP
.B balckwhite
Black to White Colour Scheme. need 256 colour.
.TP
.B bluered
Black to White Colour Scheme. need 256 colour.
.SH SEE ALSO
.BR 2048-qt (1),
.BR gnome-2048 (1).
.br
The programs are origin by mevdschee,
debian import by kokoye2007.
